/**
 * Copyright (c) 2024, 2026 TNO-ESI
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
grammar nl.esi.xtext.common.lang.Base with org.eclipse.xtext.common.Terminals

generate base "http://www.esi.nl/xtext/common/lang/Base" as base

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

BaseModel returns base::ModelContainer: {base::BaseModel}
    imports += Import*
    table = BaseTable?
;

BaseTable returns base::BaseTable: {base::BaseTable}
    Annotations
    Table
;

/*
 * Abstract class for all model containers.
 * Top level container element that may transitively import zero or more existing base models.
 * In this grammar, it is extended by the class BaseModel (see above)
 */
ModelContainer returns base::ModelContainer: {base::ModelContainer}
    imports += Import*
;

Import returns base::Import: {base::Import}
    'import' importURI = STRING
;

fragment Annotations returns base::Annotatable:
    annotations+=Annotation*
;

Annotation returns base::Annotation: {base::Annotation}
    '@' name=ID ( '(' ((params+=DefaultAnnotationParam) | (params+=AnnotationParam (',' params+=AnnotationParam)* ))? ')' )?
;

AnnotationParam returns base::AnnotationParam: {base::AnnotationParam}
    name=ID '=' value = AnnotationValue
;

DefaultAnnotationParam returns base::AnnotationParam: {base::AnnotationParam}
    value = AnnotationValue
;

AnnotationValue returns base::AnnotationValue:
      {base::AnnotationLongValue} => value=LONG
    | {base::AnnotationBooleanValue} => value=BOOL
    | {base::AnnotationStringValue} => value=STRING
    | {base::AnnotationDoubleValue} => value=DOUBLE
;

fragment Table returns base::Table:
    header = TableRow
    rows += TableRow*
;

TableRow returns base::TableRow: {base::TableRow}
    cells += TABLE_CELL+ '|'
;

/*
 * Abstract class for all NamedElements
 */
NamedElement returns base::NamedElement:
    Annotation | AnnotationParam
;

// === Terminals =======
BOOL returns ecore::EBoolean:
    'true' | 'false' | 'TRUE' | 'FALSE' | 'True' | 'False'
;

DOUBLE returns ecore::EDouble:
    INT (('.' INT) | (('E' | 'e') ('+'|'-')? INT) | ('.' INT ('E' | 'e') ('+'|'-')? INT))
;

LONG returns ecore::ELong:
    INT
;

terminal TABLE_CELL returns ecore::EString:
    '|' ('\\' !('\n'|'\r') | !('\\'|'|'|'\n'|'\r') )+
;
