/**
 * Copyright (c) 2024, 2026 TNO-ESI
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * generated by Xtext 2.36.0
 */
package nl.esi.xtext.common.lang

import com.google.inject.Injector
import nl.esi.xtext.common.lang.base.BasePackage
import org.eclipse.emf.ecore.EPackage

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BaseStandaloneSetup extends BaseStandaloneSetupGenerated {
    
    override register(Injector injector){
        if (!EPackage.Registry.INSTANCE.containsKey("http://www.esi.nl/xtext/common/lang/Base")) {
            EPackage.Registry.INSTANCE.put("http://www.esi.nl/xtext/common/lang/Base", BasePackage.eINSTANCE);
        }
        super.register(injector);
    }

	def static void doSetup() {
		new BaseStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
	
}
