/**
 * Copyright (c) 2024, 2026 TNO-ESI
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
grammar nl.esi.xtext.common.lang.Base with org.eclipse.xtext.common.Terminals

generate base "http://www.esi.nl/xtext/common/lang/Base"

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

BaseModel returns ModelContainer: {BaseModel}
    imports += Import*
    table = BaseTable?
;

BaseTable: {BaseTable}
    Annotations
    Table
;

/*
 * Abstract class for all model containers.
 * Top level container element that may transitively import zero or more existing base models.
 * In this grammar, it is extended by the class BaseModel (see above)
 */
ModelContainer: {ModelContainer}
    imports += Import*
;

Import:
    'import' importURI = STRING
;

fragment Annotations returns Annotatable:
    annotations+=Annotation*
;

Annotation: {Annotation}
    '@' name=ID ( '(' ((params+=DefaultAnnotationParam) | (params+=AnnotationParam (',' params+=AnnotationParam)* ))? ')' )?
;

AnnotationParam: {AnnotationParam}
    name=ID '=' value = AnnotationValue
;

DefaultAnnotationParam returns AnnotationParam:
    value = AnnotationValue
;

AnnotationValue:
      {AnnotationLongValue} => value=LONG
    | {AnnotationBooleanValue} => value=BOOL
    | {AnnotationStringValue} => value=STRING
    | {AnnotationDoubleValue} => value=DOUBLE
;

fragment Table returns Table:
    header = TableRow
    rows += TableRow*
;

TableRow: {TableRow}
    cells += TABLE_CELL+ '|'
;

/*
 * Abstract class for all NamedElements
 */
NamedElement:
    Annotation | AnnotationParam
;

// === Terminals =======
BOOL returns ecore::EBoolean:
    'true' | 'false' | 'TRUE' | 'FALSE' | 'True' | 'False'
;

DOUBLE returns ecore::EDouble:
    INT (('.' INT) | (('E' | 'e') ('+'|'-')? INT) | ('.' INT ('E' | 'e') ('+'|'-')? INT))
;

LONG returns ecore::ELong:
    INT
;

terminal TABLE_CELL returns ecore::EString:
    '|' ('\\' !('\n'|'\r') | !('\\'|'|'|'\n'|'\r') )+
;
