/**
 * Copyright (c) 2024, 2026 TNO-ESI
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * generated by Xtext 2.36.0
 */
package nl.esi.xtext.actions.tests

import com.google.inject.Inject
import nl.esi.xtext.actions.actions.ActionModel
import nl.esi.xtext.common.lang.utilities.EcoreUtil3
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(ActionsInjectorProvider)
class ActionsParsingTest {
    @Inject
    ParseHelper<ActionModel> parseHelper

    @Test
    def void loadModel() {
        val result = parseHelper.parse('''
            bool test = true
            if test then test := false fi
        ''')
        Assertions.assertNotNull(result)
        val errors = result.eResource.errors
        Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
    }

    @Test
    def void saveModel() {
        val input = '''
        int test = abs(-1)
        for int i in <int[]>[1,2,3] do test := test + 1 end-for'''
        val result = parseHelper.parse(input)
        EcoreUtil3.validate(result)

        val txt = EcoreUtil3.serialize(result);
        Assertions.assertEquals(input, txt)
    }

}
