/**
 * Copyright (c) 2024, 2026 TNO-ESI
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * generated by Xtext 2.10.0
 */
package nl.esi.xtext.types

import com.google.inject.Injector
import nl.esi.xtext.types.types.TypesPackage
import org.eclipse.emf.ecore.EPackage

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TypesStandaloneSetup extends TypesStandaloneSetupGenerated {

    override register(Injector injector){
        if (!EPackage.Registry.INSTANCE.containsKey("http://www.esi.nl/xtext/types/Types")) {
            EPackage.Registry.INSTANCE.put("http://www.esi.nl/xtext/types/Types", TypesPackage.eINSTANCE);
        }
        super.register(injector);
    }

	def static void doSetup() {
		new TypesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}