/**
 * Copyright (c) 2024, 2026 TNO-ESI
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * Types is one ot the root grammars. Almost all other languages extend it (directly or indirectly).
 * It defines the language for type definitions and some generic constructs reused in other 
 * languages (e.g. NamedElement, ModelContainer).
 */
grammar nl.esi.xtext.types.Types with nl.esi.xtext.common.lang.Base

generate types "http://www.esi.nl/xtext/types/Types" as types

import "http://www.esi.nl/xtext/common/lang/Base" as base
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

/*
 * Top level container element that holds type declarations.
 * In addition, it may transitively import zero or more existing type models.
 */
TypesModel returns base::ModelContainer: {types::TypesModel}
    imports += Import*
    types += TypeDecl+
;

@Override
NamedElement returns base::NamedElement:
	EnumElement | RecordField | TypeDecl
;

/*
 * The type declarations
 */
TypeDecl returns types::TypeDecl:
	EnumTypeDecl | SimpleTypeDecl | RecordTypeDecl | VectorTypeDecl | MapTypeDecl
;

NameSpace returns types::NameSpace: {types::NameSpace}
	'using' importedNamespace=QualifiedNameWithWildcard
;

QualifiedName returns ecore::EString:
    ID ('.' ID )*
;

QualifiedNameWithWildcard returns ecore::EString: 
    QualifiedName '.*'? 
;



/*
 * Simple types denote sets of values that are considered atomic.
 * User-defined simple types has no interpretation by default. An interpretation can be given
 * by providing a mapping to a type available in a target language (e.g. C++).
 * A set of built-in simple types is provided: int, bool, string, real, void, any.
 * These types are defined in the library types.types that is implicitly imported in all models.
 * int, bool, string and real have the traditional meaning.
 * void can only be used as a return type of synchronous calls.
 * any has only one value: *. * can be used in place of any other value and is used
 * to express non-determinism in parameter values. any type cannot be used directly 
 * (e.g. in event declarations, variable and other type definitions). It is used, 
 * however, in the type checker.
 * User-defined simple types can optionally be based on a built-in type. In this case
 * the type being defined can be treated as a synonym of the base type. Values of the base type
 * can be used as values of the type.
 */
SimpleTypeDecl returns types::SimpleTypeDecl: {types::SimpleTypeDecl}
    Annotations
	'type' name = ID ('based' 'on' base = [types::SimpleTypeDecl])?
;

EnumTypeDecl returns types::EnumTypeDecl: {types::EnumTypeDecl}
    Annotations
	'enum' name = ID '{' literals+=EnumElement* '}'
;

/** using integer object because it is important to see the difference
 *  between 0 (explicit 0) and null (increment + 1 from the previous value)
 */
EIntegerObject returns ecore::EIntegerObject: INT;

EnumElement returns types::EnumElement: {types::EnumElement}
    Annotations
	name = ID ('=' value = EIntegerObject)?
;

RecordTypeDecl returns types::RecordTypeDecl: {types::RecordTypeDecl}
    Annotations
	'record' name = ID ('extends' parent = [types::RecordTypeDecl])? 
	'{' (fields+=RecordField ((',')? fields+=RecordField)*)? '}'
;	

RecordField returns types::RecordField: {types::RecordField}
    Annotations
	(kind = RecordFieldKind)? type = Type name = ID
;

enum RecordFieldKind returns types::RecordFieldKind:
    CONCRETE = 'concrete' | SYMBOLIC = 'symbolic' | MIXED = 'mixed'
;

VectorTypeDecl returns types::VectorTypeDecl: {types::VectorTypeDecl}
    Annotations
	'vector' name = ID '=' constructor = VectorTypeConstructor 
;

MapTypeDecl returns types::MapTypeDecl: {types::MapTypeDecl}
    Annotations
	name = ID '=' constructor = MapTypeConstructor
;

GenericsTypeParamBase returns types::TypeDecl:
    GenericsTypeParam
;

GenericsTypeParam returns types::GenericsTypeParam: {types::GenericsTypeParam}
    name = ID
;

/*
 * Type denotes a syntactical construct (reference to a definition or an inline vector or map type)
 */
Type returns types::Type:
	TypeReference | VectorTypeConstructor | MapTypeConstructor
;

fragment TypeFR returns types::Type:
	type = [types::TypeDecl | ID]
;

MapTypeConstructor returns types::MapTypeConstructor: {types::MapTypeConstructor}
	 'map' '<' TypeFR ',' valueType = Type '>'
;

VectorTypeConstructor returns types::VectorTypeConstructor: {types::VectorTypeConstructor}
	TypeFR (dimensions += Dimension)+
;

TypeReference returns types::TypeReference: {types::TypeReference}
	TypeFR
;

Dimension returns types::Dimension:
	{types::Dimension}'['(size = INT)?']'
;

/*
 * TypeObject denotes semantic types. It is used in the type checker
 */
TypeObject returns types::TypeObject:
	{types::TypeDecl} | {types::VectorTypeConstructor} | {types::MapTypeConstructor}
;
