/**
 * Copyright (c) 2024, 2026 TNO-ESI
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * generated by Xtext 2.12.0
 */
package nl.esi.xtext.types.generator

import com.google.gson.GsonBuilder
import com.google.gson.reflect.TypeToken
import java.io.ByteArrayInputStream
import java.util.ArrayList
import java.util.List
import java.util.Map
import nl.esi.xtext.common.lang.base.Annotatable
import nl.esi.xtext.common.lang.utilities.AnnotationUtil
import nl.esi.xtext.types.types.EnumTypeDecl
import nl.esi.xtext.types.types.MapTypeDecl
import nl.esi.xtext.types.types.RecordTypeDecl
import nl.esi.xtext.types.types.SimpleTypeDecl
import nl.esi.xtext.types.types.TypeDecl
import nl.esi.xtext.types.types.TypeObject
import nl.esi.xtext.types.types.TypesModel
import nl.esi.xtext.types.types.VectorTypeDecl
import org.eclipse.emf.common.util.URI
import org.eclipse.emf.ecore.EObject
import org.eclipse.xtext.resource.XtextResourceSet

import static extension nl.esi.xtext.common.lang.utilities.AnnotationUtil.*
import static extension nl.esi.xtext.types.utilities.TypeUtilities.*
import static extension nl.esi.xtext.common.lang.utilities.EcoreUtil3.*

/**
 * Transforms types model declarations into DataTypeListEntry objects.
 * Converts from the types DSL to a platform-agnostic data model with tree structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class DataTypesOutlineGenerator {
    
    val static TRANSLATE_TYPE = Map.of("real", "Float", "int", "Int", "string", "String", "bool", "Boolean")
    val static  GSON = new GsonBuilder()
            .setPrettyPrinting()
            .disableHtmlEscaping()
            .create()

    /**
     * Transforms a TypesModel into a DataTypeListSchema with structured entries.
     */
    def static String toJson(List<DataType> model) {
        return GSON.toJson(model, new TypeToken<List<DataType>>(){}.getType())
    }

    /**
     * Deserializes a JSON string into a List of DataTypeListEntry.
     */
    def static List<DataType> fromJson(String jsonString) {
        return GSON.fromJson(jsonString, new TypeToken<List<DataType>>(){}.getType())
    }


    /**
     * Deserializes a JSON string into a List of DataTypeListEntry.
     */
    def static List<DataType> fromTypes(String rawTypes) {
        var resourceSet = new XtextResourceSet()
        var resource = resourceSet.createResource(URI.createURI("inmemory.types"))
        resource.load(new ByteArrayInputStream(rawTypes.getBytes()), null)
        resource.resolveAll
        var typesModel = resource.getContents().filter(TypesModel).head
        if (typesModel === null){
            return null
        }
        return getOutline(typesModel)
    }

    /**
     * Transforms a full TypesModel into a DataTypeListSchema with structured entries.
     */
    def static List<DataType>  getOutline(TypesModel model) {
        return model.getOutline(null)
    }

    /**
     * Transforms a TypesModel into a DataTypeListSchema with structured entries.
     * Top-level records/enums return their children directly (fields/literals) without wrapper node.
     */
    def static List<DataType> getOutline(TypesModel model, String typeName) {
        if (model === null || model.types === null) {
           return List.of
        }

        val transformer = new DataTypesOutlineGenerator()
        // return the children only if complex type else the complete entry simple type (no children)
        return model.types.filter[typeName === null || name == typeName ].map[transformer.doTransform(it)].toList
    }

    /**
     * Base dispatch method - should not be called directly.
     */
    private def dispatch DataType doTransform(TypeDecl type) {
        return new DataType(null, type.annotatedId, type.name, "?", "?", null, null, type.annotationsMap)
    }

    /**
     * Transform SimpleTypeDecl - creates a primitive type entry.
     */
    private def dispatch DataType doTransform(SimpleTypeDecl type) {
        var label = type.translatedTypeName 
        if (type.base !== null ) {
            label += " based on "  + doTransform(type.base).label
        }
        val nodeType = type.typeOrAlias(DataType.PRIMITIVE_BASED_ON)
        return new DataType(nodeType, type.annotatedId, type.name, type.translatedTypeName, label, null, null, type.annotationsMap)
    }

    /**
     * Transform EnumTypeDecl - creates an enum entry with literal children.
     */
    private def dispatch DataType doTransform(EnumTypeDecl type) {
        val literals = new ArrayList<DataType>
        val enums = type.literals
        val literalNodeType = type.typeOrAlias(DataType.ENUM_LITERAL)
        for (var int index = 0; index < enums.size; index++) {
            val literal = enums.get(index)
            val name  = literal.name
            val value = literal.value
            literals.add(new DataType(literalNodeType, literal.annotatedId, name, null, name, null, value, null, literal.annotationsMap))
        }
        val nodeType = type.typeOrAlias(DataType.ENUM)
        return new DataType(nodeType, type.annotatedId, type.name, DataType.ENUM, type.name + " : " + nodeType, null, literals, type.annotationsMap)
    }

    /**
     * Transform RecordTypeDecl - creates a record entry with field children.
     */
    private def dispatch DataType doTransform(RecordTypeDecl type) {
        val fields = new ArrayList<DataType>
        val recordFields = type.fields
        val fieldNodeType = type.typeOrAlias(DataType.RECORD_FIELD)
        for (var int index = 0; index < recordFields.size; index++) {
            val field = recordFields.get(index)
            val kind = field.kind?.literal
            val fName = field.name
            val fType = field.type
            val typeObject = fType.typeObject
            // make a copy because asTypeDecl adds the object to a Containment container
            val fieldStructure = typeObject?.asTypeDeclCopy.doTransform
            val fLabel = fieldStructure !== null ? fieldStructure.label : typeObject.translatedTypeName
            val children = fieldStructure === null ? null:  fieldStructure.children
            fields.add(new DataType(fieldNodeType, field.annotatedId, fName, typeObject.translatedTypeName, fName +" : "+fLabel, kind, children, field.annotationsMap))
        }
        val nodeType = type.typeOrAlias(DataType.RECORD)
        return new DataType(nodeType, type.annotatedId, type.name, DataType.RECORD, type.name + " : " + nodeType, null, fields, type.annotationsMap)
    }

    /**
     * Transform VectorTypeDecl - creates a collection element entry.
     */
    private def dispatch DataType doTransform(VectorTypeDecl type) {
        val children = new ArrayList<DataType>
        val elementType = type.elementType
        var childLabel = "?"
        val elementNodeType = type.typeOrAlias(DataType.COLLECTION_ELEMENT)
        if (elementType !== null) {
            val child = elementType.asTypeDeclCopy.doTransform
            children.add(new DataType(elementNodeType, elementType.annotatedId, "element", child?.label, "«element» : " + child?.label, null, child?.children, elementType.annotationsMap))
        }
        val nodeType = type.typeOrAlias(DataType.LIST)
        return new DataType(nodeType, type.annotatedId, type.name, DataType.LIST, '''List<«childLabel»>''', null, children, type.annotationsMap)
    }

    /**
     * Transform MapTypeDecl - creates a map entry with key and value children.
     */
    private def dispatch DataType doTransform(MapTypeDecl type) {
        val result = new ArrayList<DataType>
        var labels = newArrayList
        // Handle key type
        val keyType = type.keyType
        if (keyType !== null) {
            val child = keyType.asTypeDeclCopy?.doTransform()
            val mapKeyNodeType = type.typeOrAlias(DataType.MAP_KEY)
            result.add(new DataType(mapKeyNodeType, keyType.annotatedId, "key", child?.label, "«key» : " + child?.label, null, child?.children, keyType.annotationsMap))
            labels.add(child?.label)
        }
        // Handle value type
        val valueType = type.valueType
        val mapValueNodeType = type.typeOrAlias(DataType.MAP_VALUE)
        if (valueType !== null) {
            val child = valueType.asTypeDeclCopy?.doTransform()
            labels.add(child?.label)
            result.add(new DataType(mapValueNodeType, valueType.annotatedId, "value", child?.label, "«value» : " + child?.label, null, child?.children, valueType.annotationsMap))
        }
        
        val nodeType = type.typeOrAlias(DataType.MAP)
        return new DataType(nodeType, type.annotatedId, type.name, DataType.MAP, '''Map<«labels.join(", ")»>''', null, result, type.annotationsMap)
    }

    private def asTypeDeclCopy(TypeObject t){
        if (t !== null){
            return t.copy.asTypeDecl
        }
        return null
    }
    private def String getAnnotatedId(EObject type) {
        if (type instanceof Annotatable){
            val annotated = AnnotationUtil.getAnnotationValue(type, "id").orElse(null)
            return annotated
        }
        return null
    }

    private def Map<String,Object> getAnnotationsMap(EObject type) {
        if (type instanceof Annotatable){
            val annotations = newLinkedHashMap
            AnnotationUtil.getAnnotations(type).entrySet.filter[key!="id" &&  key!="typeAlias"].forEach[annotations.put(key,value)]
            return !annotations.empty ? annotations : null
        }
        return null
    }

    private def String typeOrAlias(TypeDecl type, String standard) {
        if (type instanceof Annotatable){
            val annotated = AnnotationUtil.getAnnotationValue(type, "typeAlias").orElse(null)
            if (annotated !==null){
                return annotated
            }
        }
        return standard
    }

    private def String translatedTypeName(TypeObject type) {
        val name = type.typeName
        return TRANSLATE_TYPE.getOrDefault(name,name)
    }

}
