/**
 * Copyright (c) 2024, 2026 TNO-ESI
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * generated by Xtext 2.10.0
 */
package nl.esi.xtext.expressions

import com.google.inject.Injector
import nl.esi.xtext.expressions.expression.ExpressionPackage
import org.eclipse.emf.ecore.EPackage

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExpressionStandaloneSetup extends ExpressionStandaloneSetupGenerated {

    override register(Injector injector){
        if (!EPackage.Registry.INSTANCE.containsKey("http://www.esi.nl/xtext/expressions/Expression")) {
            EPackage.Registry.INSTANCE.put("http://www.esi.nl/xtext/expressions/Expression", ExpressionPackage.eINSTANCE);
        }
        super.register(injector);
    }

	def static void doSetup() {
		new ExpressionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}