/**
 * Copyright (c) 2024, 2026 TNO-ESI
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
grammar nl.esi.xtext.expressions.Expression with nl.esi.xtext.types.Types

generate expression "http://www.esi.nl/xtext/expressions/Expression" as expr

import "http://www.esi.nl/xtext/common/lang/Base" as base
import "http://www.esi.nl/xtext/types/Types" as types

ExpressionModel returns base::ModelContainer: {expr::ExpressionModel}
    imports += Import*
    ( types += TypeDecl
    | variables += VariableDecl
    | functions += FunctionDecl
    )*
;

Variable returns expr::Variable: {expr::Variable}
    Annotations
    type = Type name = ID
;

VariableDecl returns expr::VariableDecl: {expr::VariableDecl}
    variable=Variable ('=' expression=Expression)?
;

FunctionDecl returns expr::FunctionDecl: {expr::FunctionDecl}
    Annotations
    'function' ('<' typeParams += GenericsTypeParam  (',' typeParams += GenericsTypeParam)* '>')? returnType = Type name = ID '(' (params += FunctionParam (',' params += FunctionParam)*)? ')'
;

FunctionParam returns expr::FunctionParam: {expr::FunctionParam}
    Annotations
    type = Type name = ID
;

@Override
NamedElement returns base::NamedElement:
	 Variable | FunctionDecl | FunctionParam
;

Expression returns expr::Expression: ExpressionLevel1;

ExpressionLevel1 returns expr::Expression:		// Left associativity
	ExpressionLevel2
	( ({expr::ExpressionAnd.left=current}			("AND" | "and")	right=ExpressionLevel2)  
	| ({expr::ExpressionOr.left=current}			("OR" | "or")	right=ExpressionLevel2)	
	)*
;

ExpressionLevel2 returns expr::Expression:		// Left associativity
	ExpressionLevel3
	( ({expr::ExpressionEqual.left=current}		"=="	right=ExpressionLevel3) 
	| ({expr::ExpressionNEqual.left=current}		"!="	right=ExpressionLevel3)	
	)*
;

ExpressionLevel3 returns expr::Expression:		// Left associativity
	ExpressionLevel4
	( ({expr::ExpressionGeq.left    =current}		">="	right=ExpressionLevel4) 
	| ({expr::ExpressionGreater.left=current}		">"		right=ExpressionLevel4) 
	| ({expr::ExpressionLeq.left    =current}		"<="	right=ExpressionLevel4) 
	| ({expr::ExpressionLess.left   =current}		"<"		right=ExpressionLevel4)
	)*
;

ExpressionLevel4 returns expr::Expression:		// Left associativity
	ExpressionLevel5
	( ({expr::ExpressionAddition.left   =current}	"+"		right=ExpressionLevel5) 
	| ({expr::ExpressionSubtraction.left=current}	"-"		right=ExpressionLevel5) 
	)*
;

ExpressionLevel5 returns expr::Expression:		// Left associativity
	ExpressionLevel6
	( ({expr::ExpressionMultiply.left=current}	"*"		right=ExpressionLevel6) 
	| ({expr::ExpressionDivision.left=current}	"/"		right=ExpressionLevel6)
	| ({expr::ExpressionMaximum.left =current}	"max"	right=ExpressionLevel6)
	| ({expr::ExpressionMinimum.left =current}	"min"	right=ExpressionLevel6)
	| ({expr::ExpressionModulo.left  =current}	"mod"	right=ExpressionLevel6)
	)*
;

ExpressionLevel6 returns expr::Expression:		// Right associativity
	ExpressionLevel7
	( ({expr::ExpressionPower.left=current}          "^"    right=ExpressionLevel6)
    | ({expr::ExpressionNullCoalescing.left=current} "??"   right=ExpressionLevel6)
    | ({expr::ExpressionConditional.left=current}    "?"    middle=ExpressionLevel6   ":"   right=ExpressionLevel6)
	)?
;

ExpressionLevel7 returns expr::Expression:
	ExpressionNot | ExpressionMinus | ExpressionPlus | ExpressionLevel8
;

ExpressionNot returns expr::ExpressionNot: {expr::ExpressionNot}
	("NOT" | "not") sub=ExpressionLevel8
;

ExpressionMinus returns expr::ExpressionMinus: {expr::ExpressionMinus}
	"-" sub=ExpressionLevel8
;

ExpressionPlus returns expr::ExpressionPlus: {expr::ExpressionPlus}
	"+" sub=ExpressionLevel8
;

ExpressionLevel8 returns expr::Expression:
	ExpressionLevel9 (({expr::ExpressionRecordAccess.record = current} (nullSafe?='?.' | '.') field = [types::RecordField | ID]) |
					  ({expr::ExpressionMapRW.map = current} '[' key = Expression ('->' value = Expression)? ']'))*
;

ExpressionLevel9 returns expr::Expression:
	ExpressionBracket |
	ExpressionConstantBool |
	ExpressionConstantInt |
	ExpressionConstantReal |
	ExpressionConstantString |
	ExpressionEnumLiteral |
    ExpressionNullLiteral |
	ExpressionVariable |
	ExpressionRecord |
	ExpressionAny |
    ExpressionFunctionCall |
	ExpressionTypeAnnotated
;

ExpressionFunctionCall returns expr::ExpressionFunctionCall: {expr::ExpressionFunctionCall}
    function = [expr::FunctionDecl|ID] '(' (args += Expression (',' args += Expression)*)? (',' namedArgs += NamedArgument)* ')'
;

NamedArgument returns expr::NamedArgument: {expr::NamedArgument}
    name = ID '=' arg=Expression
;

ExpressionBracket returns expr::ExpressionBracket: {expr::ExpressionBracket}
	"(" sub=Expression ")"
;

ExpressionConstantBool returns expr::ExpressionConstantBool: {expr::ExpressionConstantBool}
	value=BOOL
;

ExpressionConstantInt returns expr::ExpressionConstantInt: {expr::ExpressionConstantInt}
	value=LONG
;

ExpressionConstantReal returns expr::ExpressionConstantReal: {expr::ExpressionConstantReal}
	value=DOUBLE
;

ExpressionConstantString returns expr::ExpressionConstantString: {expr::ExpressionConstantString}
	value = STRING
;

ExpressionEnumLiteral returns expr::ExpressionEnumLiteral: {expr::ExpressionEnumLiteral}
	type = [types::EnumTypeDecl] "::" literal = [types::EnumElement] 
;

ExpressionNullLiteral returns expr::ExpressionNullLiteral:
    {expr::ExpressionNullLiteral}
    'null'
;

ExpressionVariable returns expr::ExpressionVariable: {expr::ExpressionVariable}
	variable=[expr::Variable | ID]
;

ExpressionRecord returns expr::ExpressionRecord: {expr::ExpressionRecord}
	type = [types::RecordTypeDecl] '{' fields+=Field (',' fields+=Field)* '}'
;

Field returns expr::Field: {expr::Field}
	recordField = [types::RecordField | ID] '=' exp = Expression
;

ExpressionAny returns expr::ExpressionAny: {expr::ExpressionAny}
	"*"
;

ExpressionTypeAnnotated returns expr::Expression:
	TypeAnnotation( ({expr::ExpressionVector.typeAnnotation = current} '[' (elements += Expression (',' elements += Expression)*)? ']') |
		            ({expr::ExpressionMap.typeAnnotation = current} '{' (pairs += Pair (',' pairs += Pair)*)? '}'))
;

TypeAnnotation returns expr::TypeAnnotation: {expr::TypeAnnotation}
	'<'type = Type '>'
;

Pair returns expr::Pair: {expr::Pair}
	key = Expression '->' value = Expression
;

// --- add extra superclasses in metamodel -------

ExpressionTernary returns expr::Expression:
    {expr::ExpressionTernary}
    left=Expression
    middle=Expression
    right=Expression
;

ConcreteExpressionTernary returns expr::ExpressionTernary:
    {expr::ExpressionConditional}
;

ExpressionBinary returns expr::Expression:
	{expr::ExpressionBinary}
    left=Expression
    right=Expression
;

ConcreteExpressionBinary returns expr::ExpressionBinary:
	  {expr::ExpressionAnd}
	| {expr::ExpressionOr}
	| {expr::ExpressionEqual}
	| {expr::ExpressionNEqual}
	| {expr::ExpressionGeq}
	| {expr::ExpressionGreater}
	| {expr::ExpressionLeq}
	| {expr::ExpressionLess}
	| {expr::ExpressionAddition}
	| {expr::ExpressionSubtraction}
	| {expr::ExpressionMultiply}
	| {expr::ExpressionDivision}
	| {expr::ExpressionMaximum}
	| {expr::ExpressionMinimum}
	| {expr::ExpressionModulo}
	| {expr::ExpressionPower}
	| {expr::ExpressionNullCoalescing}
;

ExpressionUnary returns expr::Expression:
	{expr::ExpressionUnary}
	sub=Expression
;

ConcreteExpressionUnary returns expr::ExpressionUnary:
	  {expr::ExpressionNot}
	| {expr::ExpressionMinus}
	| {expr::ExpressionPlus}
	| {expr::ExpressionBracket}	
;
