/**
 * Copyright (c) 2024, 2026 TNO-ESI
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * generated by Xtext 2.10.0
 */
package nl.esi.xtext.types.scoping

import com.google.common.base.Predicate
import nl.esi.xtext.types.types.Type
import nl.esi.xtext.types.types.TypeObject
import nl.esi.xtext.types.types.TypesPackage
import nl.esi.xtext.types.utilities.TypeUtilities
import org.eclipse.emf.ecore.EClass
import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.EReference
import org.eclipse.emf.ecore.EStructuralFeature
import org.eclipse.xtext.resource.IEObjectDescription
import org.eclipse.xtext.scoping.IScope
import org.eclipse.xtext.scoping.impl.FilteringScope

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class TypesScopeProvider extends AbstractTypesScopeProvider {
    /* The types as defined in types.types are bool, void, int, real, string, any and id 
     * * bool becomes a keyword in the language (see nl.esi.xtext.common.lang.Base)
     * * void has no reference
     * * any becomes a star (*) in nl.esi...exrpessions.xtext#ExpressionAny
     * * the others are handled via SIMPLE_TYPES_BASE below
     * */
    static val SIMPLE_TYPES_BASE = #{'int', 'real', 'string'}

    override getScope(EObject context, EReference reference) {
        switch (reference) {
            case TypesPackage.Literals.SIMPLE_TYPE_DECL__BASE: {
                logScope('''Filtering «SIMPLE_TYPES_BASE»''', context, reference)
                return filterScope(context, reference)[SIMPLE_TYPES_BASE.contains(name.toString)]
            }
            case reference.isTypeDeclReference: {
                val contextType = context.getContextType(reference)
                if (contextType !== null) {
                    logScope('''Filtering "«TypeUtilities.getTypeName(contextType)»"''', context, reference)
                    return filterScope(context, reference) [ desc |
                        TypeUtilities.subTypeOf(desc.EObjectOrProxy as TypeObject, contextType)
                    ]
                }
            }
        }

        logScope('Default', context, reference)
        return super.getScope(context, reference)
    }

    def protected IScope filterScope(EObject context, EReference reference, Predicate<IEObjectDescription> filter) {
        return new FilteringScope(super.getScope(context, reference), filter)
    }

    def protected TypeObject getContextType(EObject context, EStructuralFeature reference) {
        return switch (context) {
            Type case reference != TypesPackage.Literals.TYPE__TYPE : {
                context.type
            }
            default: {
                null
            }
        }
    }

    def protected isTypeDeclReference(EReference reference) {
        return reference.EType instanceof EClass && TypesPackage.Literals.TYPE_DECL.isSuperTypeOf(reference.EType as EClass)
    }

    /**
     * TODO: Please uncomment the body of this method for debugging scoping
     */
    protected def void logScope(String prefix, EObject context, EStructuralFeature reference) {
//        println('''«prefix»: «context.eClass.name»«IF reference !== null» case reference == «reference.toPackageDeclaration»«ENDIF»''')
    }

    protected def toPackageDeclaration(EStructuralFeature feature) {
        val eclassName = feature.EContainingClass.name.replaceAll('([^A-Z])([A-Z])', '$1_$2')
        val featureName = feature.name.replaceAll('([^A-Z])([A-Z])', '$1_$2')
        return '''«feature.EContainingClass.EPackage.name.toFirstUpper»Package.Literals.«eclassName.toUpperCase»__«featureName.toUpperCase»'''
    }
}
